In [14]:
import os
import sys

PROJECT_ROOT = os.path.abspath("..")

if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

In [15]:
from src.data_loader import load_dataset
from src.preprocessing import preprocess_pipeline

In [16]:
df = load_dataset()

[2026-07-01 16:25:03] Loading dataset : C:\Users\LENOVO\Documents\kuliah\smt 4\mlp\UAS\dataset\heartv1.csv
[2026-07-01 16:25:03] Dataset loaded successfully.

In [17]:
print(df.head())

      sex  age  cp  resting_BP  chol  fbs  restecg  thalach   exang  oldpeak  \
0    male   65   0         130   254    0        0       147      0      1.4
1    male   53   0         140   261    0        0       186      1      0.0
2    male   50   0         122   222    0        0       186      0      0.0
3  female   47   1         112   160    0        1       138      0      0.0
4    male   47   0         142   309    0        0       147      1      0.0

   slope  ca  thal  Max Heart Rate Reserve  Heart Disease Risk Score  target
0      1   1     3                      10                     11.44       0
1      2   0     2                     -17                     13.51       1
2      2   0     2                     -14                      9.46       1
3      1   0     2                      37                      8.34       1
4      1   3     3                      28                     13.43       0

In [18]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   sex                       1035 non-null   str
 1   age                       1035 non-null   int64
 2   cp                        1035 non-null   int64
 3   resting_BP                1035 non-null   int64
 4   chol                      1035 non-null   int64
 5   fbs                       1035 non-null   int64
 6   restecg                   1035 non-null   int64
 7   thalach                   1035 non-null   int64
 8   exang                     1035 non-null   int64
 9   oldpeak                   1035 non-null   float64
 10  slope                     1035 non-null   int64
 11  ca                        1035 non-null   int64
 12  thal                      1035 non-null   int64
 13  Max Heart Rate Reserve    1035 non-null   int64
 14  Heart Disease Risk Score  1035 non-null   float64
 15  target                    1035 non-null   int64
dtypes: float64(2), int64(13), str(1)
memory usage: 134.2 KB
None

In [19]:
print(df.describe())

               age           cp   resting_BP         chol          fbs  \
count  1035.000000  1035.000000  1035.000000  1035.000000  1035.000000
mean     56.447343     0.944928   131.663768   245.608696     0.150725
std       9.098955     1.029479    17.503716    51.532478     0.357953
min      28.000000     0.000000    94.000000   126.000000     0.000000
25%      50.000000     0.000000   120.000000   210.500000     0.000000
50%      58.000000     1.000000   130.000000   240.000000     0.000000
75%      63.000000     2.000000   140.000000   275.000000     0.000000
max      79.000000     3.000000   200.000000   564.000000     1.000000

           restecg     thalach         exang      oldpeak        slope  \
count  1035.000000  1035.000000  1035.000000  1035.000000  1035.000000
mean      0.531401   149.182609     0.338164     1.078937     1.381643
std       0.527511    22.952151     0.473313     1.174529     0.620609
min       0.000000    71.000000     0.000000     0.000000     0.000000
25%       0.000000   132.000000     0.000000     0.000000     1.000000
50%       1.000000   152.000000     0.000000     0.800000     1.000000
75%       1.000000   166.000000     1.000000     1.800000     2.000000
max       2.000000   202.000000     1.000000     6.200000     2.000000

                ca         thal  Max Heart Rate Reserve  \
count  1035.000000  1035.000000             1035.000000
mean      0.760386     2.321739               16.339130
std       1.033564     0.621862               21.140178
min       0.000000     0.000000              -29.000000
25%       0.000000     2.000000                0.000000
50%       0.000000     2.000000               12.000000
75%       1.000000     3.000000               28.000000
max       4.000000     3.000000               82.000000

       Heart Disease Risk Score       target
count               1035.000000  1035.000000
mean                  11.873952     0.513043
std                    2.235081     0.500071
min                    7.540000     0.000000
25%                   10.160000     0.000000
50%                   11.690000     1.000000
75%                   13.560000     1.000000
max                   18.800000     1.000000

In [20]:
print(df.describe())

               age           cp   resting_BP         chol          fbs  \
count  1035.000000  1035.000000  1035.000000  1035.000000  1035.000000
mean     56.447343     0.944928   131.663768   245.608696     0.150725
std       9.098955     1.029479    17.503716    51.532478     0.357953
min      28.000000     0.000000    94.000000   126.000000     0.000000
25%      50.000000     0.000000   120.000000   210.500000     0.000000
50%      58.000000     1.000000   130.000000   240.000000     0.000000
75%      63.000000     2.000000   140.000000   275.000000     0.000000
max      79.000000     3.000000   200.000000   564.000000     1.000000

           restecg     thalach         exang      oldpeak        slope  \
count  1035.000000  1035.000000  1035.000000  1035.000000  1035.000000
mean      0.531401   149.182609     0.338164     1.078937     1.381643
std       0.527511    22.952151     0.473313     1.174529     0.620609
min       0.000000    71.000000     0.000000     0.000000     0.000000
25%       0.000000   132.000000     0.000000     0.000000     1.000000
50%       1.000000   152.000000     0.000000     0.800000     1.000000
75%       1.000000   166.000000     1.000000     1.800000     2.000000
max       2.000000   202.000000     1.000000     6.200000     2.000000

                ca         thal  Max Heart Rate Reserve  \
count  1035.000000  1035.000000             1035.000000
mean      0.760386     2.321739               16.339130
std       1.033564     0.621862               21.140178
min       0.000000     0.000000              -29.000000
25%       0.000000     2.000000                0.000000
50%       0.000000     2.000000               12.000000
75%       1.000000     3.000000               28.000000
max       4.000000     3.000000               82.000000

       Heart Disease Risk Score       target
count               1035.000000  1035.000000
mean                  11.873952     0.513043
std                    2.235081     0.500071
min                    7.540000     0.000000
25%                   10.160000     0.000000
50%                   11.690000     1.000000
75%                   13.560000     1.000000
max                   18.800000     1.000000

In [21]:
data = preprocess_pipeline(df)

[2026-07-01 16:25:43] ============================================================
[2026-07-01 16:25:43] START PREPROCESSING
[2026-07-01 16:25:43] ============================================================
[2026-07-01 16:25:43] Duplicate removed : 723
[2026-07-01 16:25:43] Current rows      : 312
[2026-07-01 16:25:43] Missing values : 0
[2026-07-01 16:25:43] Rows removed : 0
[2026-07-01 16:25:43] Categorical features encoded.
[2026-07-01 16:25:43] Feature shape : (312, 14)
[2026-07-01 16:25:43] Target shape  : (312,)
[2026-07-01 16:25:43] Feature columns saved.
[2026-07-01 16:25:43] Dataset split completed.
[2026-07-01 16:25:43] Train      : 218
[2026-07-01 16:25:43] Validation : 47
[2026-07-01 16:25:43] Test       : 47
[2026-07-01 16:25:43] Scaler saved successfully.
[2026-07-01 16:25:43] Processed datasets saved successfully.
[2026-07-01 16:25:43] ============================================================
[2026-07-01 16:25:43] PREPROCESSING FINISHED
[2026-07-01 16:25:43] ============================================================

In [22]:
data.keys()

dict_keys(['train_raw', 'valid_raw', 'test_raw', 'train_scaled', 'valid_scaled', 'test_scaled', 'X_train', 'X_valid', 'X_test', 'y_train', 'y_valid', 'y_test', 'feature_columns'])

In [23]:
data["train_scaled"].head()

,sex,age,cp,resting_BP,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,Max Heart Rate Reserve,Heart Disease Risk Score
0,0.68773,-1.525689,0.075001,-0.623160,-1.670703,-0.414781,0.947645,1.391637,-0.702247,-0.937729,1.006999,-0.772334,-0.557837,-0.896591,8.07
1,0.68773,0.968246,-0.886771,-0.042857,1.550446,2.410913,-0.983071,-0.729583,1.424001,0.601229,1.006999,2.181504,1.108033,0.406145,17.20
2,0.68773,-0.618804,1.036773,-0.623160,-1.093503,-0.414781,0.947645,-0.432612,-0.702247,0.772224,-0.595379,2.181504,1.108033,0.731829,9.18
3,0.68773,-0.505443,-0.886771,1.117749,-0.069438,-0.414781,-0.983071,-0.899281,-0.702247,1.285210,-0.595379,-0.772334,1.108033,1.197091,10.43
4,0.68773,-1.865771,1.036773,0.421385,-1.335555,-0.414781,0.947645,1.009818,-0.702247,-0.937729,1.006999,3.166117,-0.557837,-0.338276,8.31

In [24]:
data["valid_scaled"].head()

,sex,age,cp,resting_BP,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,Max Heart Rate Reserve,Heart Disease Risk Score
0,0.687730,0.401442,0.075001,-0.333009,-0.497683,-0.414781,0.947645,-0.220490,-0.702247,-0.595738,-0.595379,3.166117,1.108033,0.080461,10.50
1,0.687730,0.401442,1.036773,-1.493615,-0.125296,-0.414781,-0.983071,0.203754,1.424001,-0.424743,-0.595379,-0.772334,1.108033,-0.384802,13.30
2,-1.454058,-0.505443,1.036773,-0.623160,-0.516303,-0.414781,0.947645,0.373452,-0.702247,0.430234,-0.595379,-0.772334,-0.557837,-0.198697,9.59
3,0.687730,0.401442,-0.886771,-0.971342,1.327014,-0.414781,2.878361,-0.390188,-0.702247,2.824168,-2.197757,2.181504,-2.223708,0.266566,11.26
4,0.687730,1.308328,-0.886771,-1.087403,-0.646638,-0.414781,-0.983071,-0.729583,1.424001,-0.852231,1.006999,0.212279,-0.557837,0.266566,13.96

In [25]:
data["test_scaled"].head()

,sex,age,cp,resting_BP,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,Max Heart Rate Reserve,Heart Disease Risk Score
0,-1.454058,0.288082,-0.886771,-0.623160,1.997311,-0.414781,0.947645,0.585574,1.424001,-0.424743,1.006999,-0.772334,-0.557837,-0.757012,14.64
1,-1.454058,-0.165361,-0.886771,0.421385,-0.237012,-0.414781,-0.983071,0.458300,-0.702247,-0.937729,1.006999,-0.772334,-0.557837,-0.431329,10.40
2,0.687730,0.401442,0.075001,-0.623160,0.693955,-0.414781,-0.983071,0.458300,-0.702247,0.601229,-0.595379,-0.772334,-0.557837,-0.663960,11.04
3,0.687730,0.968246,-0.886771,0.537446,-1.112122,-0.414781,-0.983071,-0.220490,1.424001,2.482177,1.006999,1.196892,1.108033,-0.152171,13.97
4,0.687730,0.288082,-0.886771,0.073203,-0.739735,-0.414781,0.947645,0.797696,1.424001,-0.937729,1.006999,-0.772334,1.108033,-0.989644,13.41

In [26]:
print("Training Dataset :", data["X_train"].shape)
print("Validation Dataset :", data["X_valid"].shape)
print("Testing Dataset :", data["X_test"].shape)

Training Dataset : (218, 14)
Validation Dataset : (47, 14)
Testing Dataset : (47, 14)

In [27]:
print(data["feature_columns"])

['sex', 'age', 'cp', 'resting_BP', 'chol', 'fbs', 'restecg', 'thalach ', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'Max Heart Rate Reserve']

In [28]:
print(data["y_train"].head())

119     8.07
269    17.20
78      9.18
816    10.43
15      8.31
Name: Heart Disease Risk Score, dtype: float64

In [29]:
print("Preprocessing completed successfully.")

Preprocessing completed successfully.